### ISSUE TITLE
Develop Website for Standardized Open Networks Agreement similar to Creative Commons

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#128]
Creative Commons is a wonderful example how standardized processes can enable millions of people to share freely. What about sharing your Internet connection? Across the world there are different legal settings and requirements for sharing of Internet connections and specifically Open Wifi connections. The Picopeering Agreement already offered a basis for completely free and open sharing: http://www.picopeer.net/

However, in many settings people cannot enable unrestricted level of sharing, e.g. if you share Internet in your office, you might need to reserve a certain bandwidth for you and restrict the bandwidth of users.

We need a website, that reflects these details and makes it transparent to the user. Just like at Creative Commons the site should generate a) a human readable file and b) a machine readable file of the level of sharing that is offered by someone. Examples are, that networks are completely free (all ports are open, all services are enabled, bandwidth is unrestricted) compared to networks with restrictions e.g. no torrent sharing, limited bandwidth and an accepted user agreement that is required.

Your task: Please propose a development plan and wireframes to implement the site, preferably in a JS technology that allows the site to be used by large number of users.

**Comment by lovemehta** [comment]
Hello Sir, 
I am interested in knowing more about the project. Can you please share any useful links that we can follow to get a better idea.
Thanks

**Comment by aero31aero** [comment]
I am interested in this project. I currently am doing database management and linking with frontend using the MEAN stack, and have used LAMP as well. 

The design can be built using simple rules that can be added by the user like "BLOCK PORTS IN RANGE 800-1000" would generate 201 lines of machine readable code, and such rules can be then stored in a database from where we can easily add new kinds of rules, as well as map ports to services so that the GUI can be used easily.

From what I understand, you could use a RESTful API to insert all these necessary rules in a database, and read them back. After that, an HTML client application using Angular/any other framework can be created. If you want me to create a Mockup using this approach, please reply. I'll have one ready in 2 days.

**Comment by mabhi684** [comment]
Hi,This is a great idea and I would like to work on it,I would like to know more about the project so that I can draft a proposal!!

**Comment by athuljayaram** [comment]
I am interested to work on this

**Comment by mariobehling** [comment]
Great. This project was started here: https://github.com/fossasia/CommonsNet

Please join.
