### ISSUE TITLE
Transition of Open-Event Server Architecture from REST to GraphQL

### ISSUE THREAD

**Issue by S2606** [fossasia/labs.fossasia.org#271]
One of the projects include adding the organizer feature for Open-Event Server. This might make the whole API bit clumsy. So maybe we could change the core of the backend server from REST to GraphQl? As we know [GraphQl](http://graphql.org/learn/) looks something like this
``````
{
author {
      name
      posts {
          title
          comments {
              comment
          }
      }
  }
}
``````
This much information we can receive just by one query thereby reducing the network requests.
Plus GraphQL also has advantages such as help in easing the request we make to these servers either from web or mobile app.

Note:-This is a very large project and can be broken into different sub-modules

**Comment by SaptakS** [comment]
@S2606 you are right on point. But I think our use case is a little different where GraphQl might not actually improve the functioning as of now. Let me explain a little. 
* The basic structure of GraphQl comes handy when the number of authors and comments and posts interacting with each other a lot. Right now that isn't exactly the case with our system. Our system has independent requirements for each endpoint separately as well. GraphQl comes handy when the nodes have much more interconnectivity. Right now I feel, changing the convention won't benefit a lot.
* GraphQl really makes a difference when the number of nodes is huge. In our case, though an event might have lots of sessions, the number of events isn't huge, and the interconnectivity among events and sessions of events is almost null. GraphQl is handier when there are many authors making many posts and everyone interacting with each other's post. In our case, organizers will hardly interact with each other's events.
* This reason is more of a personal opinion. I would suggest that first, we complete implementation and features in REST API since it can be added much easily and clearly. GraphQl would require changes in Infra side as well. And I think that change is much more huge compared to the benefit we might get out of it.

Having said that, there might be parts where we need GraphQl. Also, a lot depends on @fossasia/open-event-frontend and their implementations. So if to implement certain things the number of requests is huge and causing a lag, then obviously we might need GraphQl. Right now I feel it's like using a cannon to kill a rat. That's all/

**Comment by S2606** [comment]
@SaptakS Thank you for your response.I just had a doubt.What is the difference between open-event-server and open-event-legacy?

**Comment by SaptakS** [comment]
@S2606 open-event-legacy is the code which is in production right now. But the current work is going on in open-event-server. As soon as open-event-server is beta ready, we will start migrating to the new code and move away from the legacy code.

**Comment by shubham-padia** [comment]
Personally, for something of the scale of badgeyay, graphQL seems like overkill.
