### ISSUE TITLE
Create a Web Interface for PSLab

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#284]
Currently the PSLab can be accessed through a desktop platform and an Android platform. The desktop platform limits the device usage only to Linux based users and the Android platform limits the use of device to Android based users. In order to expand the use of device, a web platform will allow access to any user regardless whatever the platform he is in.

PSLab uses UART communication and the firmware will give an idea of how this communication is happening and what command to issue to perform each functionality. We are suggesting to develop a Node.js application to create the back-end for the web interface.

The expected outcome of this idea is to develop a web interface which is similar in functionality to both the PSLab Android application as well as the Android desktop application.

Repository: https://github.com/fossasia/pslab

Website: http://pslab.fossasia.org

**Comment by thisisayush** [comment]
Hi @mariobehling ,
I want to apply for GSoC 2018 under FOSSASIA, came across this project, the task includes developing a web application for PSLab. I have been working in Web Development for 2+ years and have worked on Python and Django for an year.
The project suggests creating NodeJs Application, however, I suggest creating the backend on Django (Python), so that the existing methods from pslab-python can be used without the need of porting the code to NodeJs.

Request your views on the same.

**Comment by rameela20** [comment]
Creating a Nodejs applications means we have to create REST APIs for each requests depending on the backend task specified right @mariobehling 
So accessing a web service can be done through almost any platform nowadays.I am interested in this to be implemented as Gsoc project

**Comment by rameela20** [comment]
So should I implement REST API for all the functions currently done in android/desktop app? Any priorities? @mariobehling
