### ISSUE TITLE
Image not resized properly

### ISSUE THREAD

**Issue by Hackerbone** [fossasia/labs.fossasia.org#311]
**Image is not properly resized as shown below:**

![screenshot 2018-11-08 at 10 58 37 am](https://user-images.githubusercontent.com/20267705/48179505-88131280-e345-11e8-982a-d6aa29767e77.png)

I would like to work on this Issue.

**Comment by Hackerbone** [comment]
Umm sorry I am still working on this one..

**Comment by mariobehling** [comment]
This image is only a placeholder and should be changed with an image that is more relevant. So, the problem is more the image itself than the CSS. If you change the CSS don't change the style of the page, but only the image resizing. You can open a relevant issue, if you think you have another approach as written above. Thanks.
