### ISSUE TITLE
Develop Neurolab features on Android

### ISSUE THREAD

**Issue by mariobehling** [fossasia/labs.fossasia.org#353]
The goal of the Neurolab project is to develop an easy to use open hardware measurement headset device for brain waves that can be plugged into an Android smartphone and a software application and enables us to understand our brains better.

Our brains communicate through neurotransmitters and their activity emits electricity. The neuroheadset measures that electricity on the skin of the forehead and the software processes the signal so that it can translated into a visual or auditory representation. The data that can be collected can be analysed to identify mental health, stress, relaxation and even diseases like Alzheimer.

Current devices in the medical industry are usually not accessible by doctors due to their high pricing. They are also complicated to use. The idea of the device is to integrate it into a headband and focus on signals that can be obtained through the frontal lobe.

A difference to existing projects like OpenBCI is that it will not be necessary to 3D print large headsets. Instead we are focusing on creating a device that collects as much data as possible through the forehead. To achieve this goal we are using high-grade sensors and flexible electronics.

**Required Features to be Developed**

* Implement Neurolab visual feedback in Android app
* Implement Neurolab audio feedback in Android app

**Required Knowledge**

Android, Java, Kotlin

**Possible Mentors**

Areeb Jamal, Padmal M, Eden Jay, Willi D., Hirose Ko

**Repositories and Issue Tracker**

Neurolab Android https://github.com/fossasia/neurolab-android
Neurolab Desktop https://github.com/fossasia/neurolab-desktop
Neurolab Firmware https://github.com/fossasia/neurolab-firmware
Neurolab Hardware https://github.com/fossasia/neurolab-hardware

**Comment by Davide95** [comment]
Hi. I'm here because this year I would like to apply for GSOC and I saw this proposal [here](https://labs.fossasia.org/ideas.html).

My name is Davide, I’m an MSc student of Computer Science and I’ve a BSc in Computer Science. I've an "Associate Android Developer" certification issued by Google (http://bcert.me/smlgvwuu) that I think it'll help me implementing the requested features inside the app. For more information about me, check https://www.linkedin.com/in/driva95/ or https://github.com/Davide95.

My questions are:

* what are the prerequisites?
* can I do something now to learn more?

Thanks in advance.

**Comment by itsSiddharthGupta** [comment]
Hello @mariobehling I am interested in contributing to neurolab-android app, but cannot get it clearly what features are required for the development and what functionalities are required by the app.
Can you please explain?

**Comment by CloudyPadmal** [comment]
Hello all! Thank you for your interest in this project. To get you started, please have a look at this project. https://github.com/fossasia/neurolab-desktop 

I would encourage you to set it up and install in your computer. IntelliJ or Eclipse IDEs would be ideal for this. Run this app to see how the Neurolab desktop application looks like. There is a simulation option where you can see all the settings and data we are expecting to capture (i.e. signal frequencies, ranges etc.)

In this project, we are going to build up a similar app in Android. Hardware development is in progress.

**Comment by itsSiddharthGupta** [comment]
@CloudyPadmal i don't know how to run neurolab-desktop using eclipse. My build is successful but dont know how can i create an executable file to install it in my laptop. Can you please help me!!!!!

**Comment by lilliCao** [comment]
> Hello all! Thank you for your interest in this project. To get you started, please have a look at this project. https://github.com/fossasia/neurolab-desktop
> 
> I would encourage you to set it up and install in your computer. IntelliJ or Eclipse IDEs would be ideal for this. Run this app to see how the Neurolab desktop application looks like. There is a simulation option where you can see all the settings and data we are expecting to capture (i.e. signal frequencies, ranges etc.)

hi, I found the project very interesting and would like to contribute. But I met some basic problem on how the app works.
I did install and run both desktop app and the current android app base. Since there is no comment in code, I got really hard time try to figure out how thing works. I followed your instruction to run the demo (run Launcher and chose simulation mode) but there are not much to see except some empty windows. Is there any other documentation related to the topic. Or at least any description about  concrete things the application captures. Since there is no hardware available for testing, a docu/guideline would be nice.

**Comment by lilliCao** [comment]
@mariobehling @CloudyPadmal
